### ISSUE TITLE
Shape is converted to NumPy 64-bit integers

### ISSUE THREAD

**Issue by jakirkham** [dask-image/dask-ndfilters#26]
It seems that somehow the filters here can result in changing the array shape from a `tuple` of `int`s to a `tuple` of `numpy.int64`s. Not entirely sure how this is happening. Also am not entirely sure if this is a bug in our code or in Dask. However am able to reproduce this quite reliably.

Code snippet:

<details>

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: import dask_ndfilters as da_ndf

In [4]: a = da.ones((101, 102, 103), dtype=int, chunks=(10, 11, 12))

In [5]: da_ndf.maximum_filter(a, 3)
Out[5]: dask.array<trim, shape=(101, 102, 103), dtype=int64, chunksize=(10, 11, 12)>

In [6]: type(da_ndf.maximum_filter(a, 3).shape[0])
Out[6]: numpy.int64

In [7]: a.map_overlap(lambda x: x, depth={0: np.int64(1), 1: np.int64(1), 2: np.int64(1)})
Out[7]: dask.array<trim, shape=(101, 102, 103), dtype=int64, chunksize=(10, 11, 12)>

In [8]: type(a.map_overlap(lambda x: x, depth={0: np.int64(1), 1: np.int64(1), 2: np.int64(1)}).shape[0])
Out[8]: numpy.int64
```

</details>

<br>
Environment details:
<br>
<br>

<details>

```yaml
name: dsk_sp
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::alabaster=0.7.10=py27_0
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::babel=2.3.4=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::backports_abc=0.5=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::bokeh=0.12.5=py27_0
- conda-forge::boto3=1.4.4=py27_0
- conda-forge::botocore=1.5.39=py27_0
- conda-forge::ca-certificates=2017.1.23=1
- conda-forge::certifi=2017.4.17=py27_0
- conda-forge::click=6.7=py27_0
- conda-forge::cloudpickle=0.2.2=py27_2
- conda-forge::coverage=4.3.4=py27_0
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::dask=0.14.3=py27_0
- conda-forge::dask-ndfilters=0.1.0=py27_0
- conda-forge::dask-ndfourier=0.1.1=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::distributed=1.16.0=py27_0
- conda-forge::docutils=0.13.1=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::freetype=2.7=1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::futures=3.0.5=py27_0
- conda-forge::graphviz=2.38.0=4
- conda-forge::heapdict=1.0.0=py27_0
- conda-forge::imagesize=0.7.1=py27_0
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jmespath=0.9.2=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::locket=0.2.0=py27_1
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::matplotlib=2.0.0=np112py27_3
- conda-forge::msgpack-python=0.4.8=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pandas=0.19.2=np112py27_1
- conda-forge::partd=0.3.7=py27_0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pip=9.0.1=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::psutil=5.2.1=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::py=1.4.33=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pyparsing=2.2.0=py27_0
- conda-forge::pytest=3.0.7=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::python-graphviz=0.6=py27_1
- conda-forge::pytz=2017.2=py27_0
- conda-forge::pyyaml=3.12=py27_1
- conda-forge::readline=6.2=0
- conda-forge::requests=2.13.0=py27_0
- conda-forge::s3fs=0.0.9=py27_0
- conda-forge::s3transfer=0.1.10=py27_1
- conda-forge::scandir=1.5=py27_1
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::snowballstemmer=1.2.1=py27_0
- conda-forge::sortedcontainers=1.5.3=py27_0
- conda-forge::sphinx=1.5.5=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_1
- conda-forge::subprocess32=3.2.7=py27_0
- conda-forge::tblib=1.3.2=py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::toolz=0.8.2=py27_0
- conda-forge::tornado=4.5.1=py27_0
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zict=0.1.1=py27_0
- conda-forge::zlib=1.2.11=0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
```

</details>
