### ISSUE TITLE
Dask's stack/concatenate duplicates last result in list comprehension

### ISSUE THREAD

**Issue by jakirkham** [dask-image/dask-ndfilters#28]
Seems there is some strange behavior when using Dask's `stack` or `concatenate` with a list comprehension where it replaces each array that was stacked or concatenated with the last one computed. Below provides a few different approaches to computing the same filter and demonstrates that the final result differs when Dask's `stack` or `concatenate` is used. This is also compared to NumPy's `stack` and `concatenate`, which don't have the same issue.

FWICT this does not appear to be an issue with `dask-ndfilters`, but am opening this here for two reasons. First was unable thus far to come up with a Dask only example that reproduces this behavior. Second even if this is an issue in Dask, `dask-ndfilters` may need to implement some sort of workaround for this behavior.

Code snippet:

<details>

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: import dask_ndfilters as da_ndf

In [4]: a = np.random.random((10, 12, 14))

In [5]: d = da.from_array(a, chunks=(5, 6, 7))

In [6]: d1 = da_ndf.median_filter(d, (1, 3, 3))

In [7]: l2s = [da_ndf.median_filter(d[i], 3) for i in xrange(len(d))]

In [8]: l2c = [da_ndf.median_filter(d[i], 3)[None] for i in xrange(len(d))]

In [9]: d2s = da.stack(l2s)

In [10]: d2c = da.concatenate(l2c)

In [11]: (d1.compute() == np.stack(l2s)).all()
Out[11]: True

In [12]: (d1.compute() == np.concatenate(l2c)).all()
Out[12]: True

In [13]: (d1.compute() == d2s.compute()).all()
Out[13]: False

In [14]: (d1.compute() == d2c.compute()).all()
Out[14]: False

In [15]: (d1[-1].compute() == d2s[-1].compute()).all()
Out[15]: True

In [16]: (d1[-1].compute() == d2c[-1].compute()).all()
Out[16]: True

In [17]: (d1[-1].compute() == d2s[0].compute()).all()
Out[17]: True

In [18]: (d1[-1].compute() == d2c[0].compute()).all()
Out[18]: True
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: dsk_sp
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::alabaster=0.7.10=py27_0
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::babel=2.3.4=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::backports_abc=0.5=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::bokeh=0.12.5=py27_0
- conda-forge::boto3=1.4.4=py27_0
- conda-forge::botocore=1.5.39=py27_0
- conda-forge::ca-certificates=2017.1.23=1
- conda-forge::certifi=2017.4.17=py27_0
- conda-forge::click=6.7=py27_0
- conda-forge::cloudpickle=0.2.2=py27_2
- conda-forge::coverage=4.3.4=py27_0
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::dask=0.14.3=py27_0
- conda-forge::dask-ndfilters=0.1.1=py27_0
- conda-forge::dask-ndfourier=0.1.1=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::distributed=1.16.0=py27_0
- conda-forge::docutils=0.13.1=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::freetype=2.7=1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::futures=3.0.5=py27_0
- conda-forge::graphviz=2.38.0=4
- conda-forge::heapdict=1.0.0=py27_0
- conda-forge::imagesize=0.7.1=py27_0
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jmespath=0.9.2=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::locket=0.2.0=py27_1
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::matplotlib=2.0.0=np112py27_3
- conda-forge::msgpack-python=0.4.8=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pandas=0.19.2=np112py27_1
- conda-forge::partd=0.3.7=py27_0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pip=9.0.1=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::psutil=5.2.1=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::py=1.4.33=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pyparsing=2.2.0=py27_0
- conda-forge::pytest=3.0.7=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::python-graphviz=0.6=py27_1
- conda-forge::pytz=2017.2=py27_0
- conda-forge::pyyaml=3.12=py27_1
- conda-forge::readline=6.2=0
- conda-forge::requests=2.13.0=py27_0
- conda-forge::s3fs=0.0.9=py27_0
- conda-forge::s3transfer=0.1.10=py27_1
- conda-forge::scandir=1.5=py27_1
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::snowballstemmer=1.2.1=py27_0
- conda-forge::sortedcontainers=1.5.3=py27_0
- conda-forge::sphinx=1.5.5=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_1
- conda-forge::subprocess32=3.2.7=py27_0
- conda-forge::tblib=1.3.2=py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::toolz=0.8.2=py27_0
- conda-forge::tornado=4.5.1=py27_0
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zict=0.1.1=py27_0
- conda-forge::zlib=1.2.11=0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
```

</details>
